# Generated by Django 3.0.3 on 2020-02-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='', max_length=200),
        ),
    ]
