# Generated by Django 3.0.3 on 2020-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20200219_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='product_category',
            field=models.CharField(default='A0001', max_length=200),
        ),
    ]
